In [1]:
import pandas as pd

In [2]:
def calculate_descriptive_stats(data):
    stats_dict = {}
    #Calculate mean
    stats_dict['mean'] = data.mean()
    #Calculate median
    stats_dict['median'] = data.median()
    #Calculate mode
    if data.dtype == 'object':
        stats_dict['mode'] = data.mode()[0]
    else:
        stats_dict['mode'] = pd.Series.mode(data)
    #Calculate standard deviation
    stats_dict['std_dev'] = data.std()

    return stats_dict

from sklearn.linear_model import LinearRegression

In [3]:
import numpy as np
a = np.array([1,2,3])  
print(a)

[1 2 3]


In [4]:
a = np.array([[1,  2],  [3,  4]])
print(a)

[[1 2]
 [3 4]]


In [5]:
#  ndmin:最小维度
a = np.array([1,  2,  3,4,5], ndmin =  2)  
print(a)

[[1 2 3 4 5]]


In [6]:
# dtype 数组的所需数据类型，可选。
# 整数类型:

# int8：有符号8位整数
# int16：有符号16位整数
# int32：有符号32位整数
# int64：有符号64位整数
# uint8：无符号8位整数
# uint16：无符号16位整数
# uint32：无符号32位整数
# uint64：无符号64位整数
# 浮点数类型:

# float16：半精度浮点数
# float32：单精度浮点数
# float64：双精度浮点数
# float128：扩展精度浮点数
# 复数类型:

# complex64：由两个32位浮点数表示的复数
# complex128：由两个64位浮点数表示的复数
# complex256：由两个128位浮点数表示的复数
# 其他类型:

# bool：布尔值类型，可以是True或False
# object：Python对象类型
# string_：字符串类型
# unicode_：Unicode字符串类型
# 日期和时间类型:

# datetime64：日期和时间类型
# 自定义数据类型:

# NumPy还允许创建自定义数据类型，可以根据需要指定数据类型的大小和字节顺序。
# windows多行注释：ctrl+/
a = np.array([1,  2,  3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [7]:
dt = np.dtype(np.int32)  
print(dt)

#int8，int16，int32，int64 可替换为等价的字符串 'i1'，'i2'，'i4'，以及其他。 
dt = np.dtype('i4')  
print(dt)

int32
int32


In [8]:
# 创建结构化数据类型
dt = np.dtype([('age',np.int8)])  
print(dt)

[('age', 'i1')]


In [9]:
# 将其应用于 ndarray 对象
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt)  
print(a)

# 文件名称可用于访问 age 列的内容 
print(a['age'])

[(10,) (20,) (30,)]
[10 20 30]


In [10]:
student = np.dtype([('name','S20'),  ('age',  'i1'),  ('marks',  'f4')])  
print(student)

a = np.array([('abc',  21,  50),('xyz',  18,  75)], dtype = student)  
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [11]:
# ndarray.shape 包含数组维度的元组，它也可以用于调整数组大小。
a = np.array([[1,2,3],[4,5,6]])  
print(a.shape)

(2, 3)


In [12]:
a = np.array(([[1,2,3],[4,5,6]]) a.shape = (3,2))
print(a)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (647361457.py, line 1)